server:
   port: 9000
spring:
   application:
      name: springboot-study
   datasource:
      url: jdbc:mysql://localhost:3306/java/personal_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: root
      password: z8h0a2n3love
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
   config: classpath:log4j2.xml


